//读取文件
const fs = require('fs');
// 将 js 代码解析为ast
const parser = require("@babel/parser");
//遍历语法树
const traverse = require("@babel/traverse").default;
// 这个可以生成想要的节点类型
const t = require("@babel/types");
// ast 转化为 js 代码
const generator = require("@babel/generator").default;

const jsCode = fs.readFileSync("fm.js", {encoding: "utf-8"});

QQ0O0 = [
    "E",
    "Times",
    "hPzQanwhjOPRiyplMaUeJq",
    "application/json",
    "_TDvi",
    "zSHLIDELjIhriK7AeLUeJqfN",
    "normal.js",
    "MYRIAD PRO",
    "MS Reference Sans Serif",
    "Network error.There is a network exception",
    "application/hwepass2001.installepass2001",
    "tddf",
    "InstallTrigger",
    "1234567890",
    "language",
    "compatible",
    "task",
    "https://static.trustdecision.com/v3/3_8",
    "_TDtest",
    "arguments",
    "callPhantom",
    "/checkout",
    "H",
    "Base64",
    "-",
    "cacheKeyBlackboxTimestamp",
    "concat",
    "Segoe UI Semibold",
    "getCurrentPosition",
    "L",
    "compile",
    "screenTop",
    "hasOwnProperty",
    "Andale Mono",
    "pushNotification",
    "z6HCaKEgjthiY3pbePDpbFxmhPHlan",
    "baseFonts",
    "can't find _fmOpt",
    "Android",
    "__BROWSERTOOLS_DOMEXPLORER_ADDED",
    "sort",
    "Chrome",
    "open",
    "async",
    "destination",
    "keys",
    "finally",
    "kdf",
    "q652mrpq0k",
    "zxHLIXE7juh9HF7AMaCcbKxizsOw",
    "knee",
    "currentSrc",
    "readPixels",
    "w3",
    "gCcJ",
    "createBuffer",
    "Android.*(wv|.0.0.0)",
    "channelInterpretation",
    "ADAA95D58EB9AAF5",
    "functionlog(){[nativecode]}",
    "zPHpanwXjOPFHq7FMZUEbX",
    "zNHpaEELjIhwYOpAMNecJqfs",
    "enumerable",
    "iterations",
    "toUpperCase",
    "phantomjs",
    "z1HCIwEctLhrGF7FeNUEJd",
    "newValue",
    "tongdun.net/",
    "ch",
    "hPHjIXEGjuhiiG7AeGCf",
    "appKey",
    "success",
    "token",
    "zJMu",
    "Image",
    "zcHpINwhjuPSG3",
    "POST",
    "font",
    "reverse",
    "_handled",
    "Lucida Handwriting",
    "collectBehavior",
    "version",
    "MACAddress",
    "cacheKeyUid",
    "aHR0cDovLzEyNy4wLjAuMTo=",
    "enc",
    "zding_",
    "=",
    "API error.",
    "e8e328d27d9866dcf49ed2e0bb7411c4",
    "battery",
    "307",
    "r",
    "ratio",
    "Consolas",
    "0123456789",
    "indexOf",
    "lib",
    "allSettled",
    "numItems",
    "storage",
    "fullVersionList",
    "estimate",
    "getOwnPropertyDescriptors",
    "fulfilled",
    "relatedAddress",
    "Gult",
    "mobile",
    "hczmaKxeRLPSY371ey",
    "LUCIDA GRANDE",
    "CSS",
    "i",
    "w",
    "compileShader",
    "ubid",
    "behaviorDataTimestamp",
    "MS PGothic",
    "isEdge",
    "Lucida Fax",
    "alphabetic",
    "HzEu",
    "#f60",
    "userAgentData",
    "propertyIsEnumerable",
    "setDate",
    "abcdefghigklmn",
    "Promise.any accepts an array",
    "plugins",
    "fl",
    "0",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
    "data",
    "saveData",
    "durations",
    "removeEventListener",
    "Microsoft Sans Serif",
    "top",
    "__nightmare",
    "_xid",
    "requestPermission",
    "msBattery",
    "B",
    "stringify",
    "eruda",
    "zbHLaQEhjChrGMpYNaUEbjfgzRHC",
    "parse",
    "Malformed UTF-8 data",
    "mimeTypes",
    "miniprogram",
    "h1zjawwrtOhqYy71MQ",
    "numberOfOutputs",
    "jsDownloadedTime",
    "htHdaQwhjBhHGZ7W",
    "C558A907FD012439",
    "webgl",
    "HTMLScriptElement",
    "connection",
    "X",
    "Lucida Sans Unicode",
    "resolve",
    "Segoe Script",
    "Times New Roman PS",
    "8",
    "title",
    "position",
    "release",
    "Comic Sans",
    "zVzDIoxXjuPSGM7FePU5",
    "absolute",
    "warn",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "_data",
    "load",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+_=",
    "]",
    "Unknown error.Unknown server error",
    "Gecko",
    "getElementsByTagName",
    "createOffer",
    "en-US",
    "xxIdKey",
    "Helvetica Neue",
    "_key",
    "qrkd",
    "hash128",
    "remove",
    "Traffic limit.",
    "base64_map",
    "hbRmawwXjzhFYyHFeQ",
    "zPHda1EGjlPIHx7FeQCfbp",
    "Century Schoolbook",
    "fpVersion",
    "sKrB",
    "Arial MT",
    "innerWidth",
    "Object.keys called on non-object",
    "Garamond",
    "5",
    "_rBlock",
    " ",
    "Segoe Print",
    "mozBattery",
    "pvft",
    "mmmmmmmmmmlli",
    "getElementById",
    "constructor",
    "fillStyle",
    "A promise cannot be resolved with itself.",
    "exports",
    "zRHwIKOXjzhrYG7b",
    "isArray",
    "offsetWidth",
    "_mode",
    "Webkit",
    "jmks",
    "cbur",
    "htHdIwEFjzhiGM",
    "obsField",
    "threshold",
    "getOwnPropertyDescriptor",
    "zJHpanEFRuhLYx7AMN",
    "onRejected",
    "deviceRiskScore",
    "HpMx",
    "uniformOffset",
    "360SE",
    "_t16",
    "host",
    "netscape",
    "screen",
    "trustdecision.com/",
    "ethernet",
    "MS Serif",
    "Impact",
    "fmTest",
    "sin",
    "_xformMode",
    "z1HdawEcjuhiGPqYMQCpbKx9z0",
    "exec",
    "set",
    "jsonUrl",
    "vendor",
    "Content-Type",
    "function()",
    "iceGatheringState",
    "bb",
    "qhjc",
    "initialized",
    "Z",
    "outerWidth",
    "z1zjINELjGhLGP7A",
    "replaceState",
    "webkitRTCPeerConnection",
    "split",
    "getDocumentReferrer",
    "p",
    "_des1",
    "readyState",
    "zPHpanwXjOPFHP7aoQUiJgxmi10wkExeRLPSY371ey",
    "quota",
    "_fb",
    "getObsField",
    "frequencyBinCount",
    "jsType",
    "hPHjIXEGjuhiiY7aePUA",
    "zbHlaMEC",
    "zSHLaXwGjtQIY37Wez",
    "https://xx.com",
    "createOscillator",
    "E0701BBE33D9FD0A",
    "localStorage",
    "languages",
    "zIHlanwhRIr9Y3pYMQ",
    "uniform2f",
    "Arial Narrow",
    "setRequestHeader",
    "bxid",
    "Ebdl",
    "WbemScripting.SWbemLocator",
    "EEA83D031A653071",
    "uCMl",
    "path is not a string",
    "Cambria",
    "ucapi",
    "timestamp",
    "z0HLaMEYjKhFYSpbe4Ueb6",
    "outerHeight",
    "close",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
    "removeChild",
    "HmacMD5",
    "key",
    "DES",
    "pad",
    "YXIgTl84MDZiMzUgPSB3aW5kb3cuTm90aWZpY2F0aW9u",
    "Alipay",
    "algo",
    "getBattery",
    "gamma",
    "SerializableCipher",
    "/behavior/profile/config?platform=web&partnerCode=",
    "__vconsole",
    "showModalDialog",
    "Segoe UI Light",
    "_cipher",
    "enabled",
    "hPHjIXEGjuhiHP7aMr",
    "checkStatus",
    "k",
    "FontListToUse",
    "unable to locate global object",
    "https://us-behavior.apitd.net",
    "query and body is empty",
    "0123456789abcdef",
    "Win32",
    "mm",
    "rgba(102, 204, 0, 0.7)",
    "http://fp.fraudmetrix.cn",
    "appName",
    "ct",
    "canvas-fingerprint-defender-alert",
    "e",
    "values",
    "test",
    "charAt",
    "BlockCipher",
    "oncomplete",
    "level",
    "sign failed",
    "4enw49pim03",
    "zSHpINEGSLhwYK7AoGUeJqxezVzm",
    "Wingdings 3",
    "application/x-www-form-urlencoded",
    "useProgram",
    "UC",
    "strictMode",
    "getinfo",
    "_value",
    "Pgwz",
    "maxTouchPoints",
    "any",
    "startRendering",
    "o8gm8qu97as",
    "x-google-chrome-pdf",
    "h0HLaXEFjCQFGPple4U5bE",
    "All promises were rejected",
    "every",
    "stack",
    "WebView",
    "win",
    "isGecko",
    "~/",
    "timer",
    "Wingdings 2",
    "Edg/",
    "https://static.trustdecision.com/tdfp/us/",
    "platform",
    "behaviorUrl",
    "sealedResult",
    "Hasher",
    "errors",
    "O",
    "replace",
    ".",
    "length",
    "_x64Add",
    "post",
    "offerToReceiveAudio",
    "1",
    "_k16",
    "useSid",
    "zNHpanwGjBhLYMpbMzCpbFft",
    "_selenium",
    "buffer",
    "t",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "_TDfactor",
    "_subKeys",
    "callee",
    "_x64Fmix",
    "_x64Rotl",
    "C",
    "innerHTML",
    "ghijklmnopqrstuv",
    "Possible Unhandled Promise Rejection:",
    "initEvent",
    "h0HLaXxrSLrF",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
    "findIndex",
    "6",
    "usageDetails",
    "iceServers",
    "b",
    "TRIANGLE_STRIP",
    "j",
    "sv",
    "00000000",
    "acceleration",
    "M",
    "cookie",
    "8.0",
    "webgl-fingerprint-defender-alert",
    "zbHpIXEhRthLGZ7AoNUeb6xgh1zwIXEGjlhFG3",
    "z1zmaWOLRm",
    "longitude",
    "location",
    "onFulfilled",
    "getError",
    "y",
    "PKzx",
    "webkitAudioContext",
    "en-US,en",
    "Segoe UI Symbol",
    "setLocalDescription",
    "PkAF",
    "/",
    "qwermnbv",
    "zSHlaKwGjGhrYppboQUiJgxm",
    "^^",
    "font-fingerprint-defender",
    "cdu",
    "3",
    "isBlink",
    "behaviorConfig",
    "ongestureend",
    "o",
    "find",
    "cookieEnabled",
    "s",
    "proxyDetection",
    "pdf",
    "brands",
    "removeHandler",
    "forEach",
    "x",
    "_invSubKeys",
    "factor",
    "K",
    "zPHpanwXjOPF",
    "\"function() {\\n      if (script.dataset.active === 'true') {\\n        try {\\n          this.manipulate();\\n        }\\n        catch(e) {\\n          console.warn('manipulation failed', e);\\n        }\\n      }\\n      return toDataURL.apply(this, arguments);\\n    }\"",
    "defineobjectproperty",
    "AggregateError",
    "SDK error.The current environment is not compatible",
    "textBaseline",
    "reject",
    "Promise.all accepts an array",
    "zbHLa1EFjUPI",
    "screenY",
    "opr",
    "altitude",
    "zNHQaIEGSLPwGq7AoHUJJdfj",
    "min",
    "Console",
    "queryUsageAndQuota",
    "apiStatus",
    "normalUrl",
    "PvtK",
    "Decryptor",
    "d",
    "Arial Rounded MT Bold",
    "h1zjawwrtOhqYy71MQefbjfjzV",
    "Unknown error.The response data is missing",
    "zufs",
    "Unknown error.Result is illegal",
    "Date",
    "wfb",
    "initStorage",
    "GET",
    "gk",
    "_Selenium_IDE_Recorder",
    "createProgram",
    "Courier New",
    "wk",
    "_$el",
    "h",
    "ExecQuery",
    "salt",
    "DateTimeFormat",
    "LAjt",
    "&",
    "iframe",
    "openDatabase",
    "channelCountMode",
    "slice",
    "_phantom",
    "62BB9B5EB31B00B0",
    "V",
    "createAnalyser",
    "YXV0b21hLXBhbGV0dGU=",
    "latitude",
    "caller",
    "functionget",
    "WEBGL_debug_renderer_info",
    "_x64Xor",
    "position:absolute !important; z-index:-9999 !important; visibility:hidden !important;border:0 !important",
    "zxHLIXE7juh9iFplePUaldxaz6HLanwh",
    "webgl-fingerprint-defender",
    "this is null or not defined",
    "_checkout",
    "_not_checkout",
    "P",
    "item",
    "RequestFileSystem",
    "functionget(){[nativecode]}",
    "setItem",
    "_state",
    "zNHpaKOkjLhIGZ7AMNCc",
    "userAgentDataStr",
    "20030107",
    "isIE",
    "Trebuchet MS",
    "channel",
    "fe",
    "wm",
    " is not a function",
    "Tahoma",
    "addEventListener",
    "PasswordBasedCipher",
    "type",
    "4.1.1",
    "wasmSupport",
    "functiontoString(){[nativecode]}",
    "_des2",
    "zVzDIoOejKhIYyH1eTUabF",
    "private",
    "abcdefghjiklmnopqrstuvwxyz",
    "MS Sans Serif",
    "function",
    "hyhbgqbaxi6",
    "Lucida Sans Typewriter",
    "f",
    "addHandler",
    "ve",
    "noIframe",
    "4",
    "amap",
    "push",
    "600",
    "-webkit-hyphens",
    "Wingdings",
    "cacheKeyBlackbox",
    "$super",
    "gbCC",
    "mac",
    "audiocontext-fingerprint-defender",
    "_utf8_encode",
    "toLocaleString",
    "webgl-defender-alert",
    "onicecandidate",
    "substr",
    "Network error.The SDK response times out ",
    ", ",
    "f736mgcni9c",
    "message",
    "sdkVersion",
    "pushState",
    "StyleMedia",
    "application/vnd.chromium.remoting-viewer",
    "normal",
    "isWebkit",
    "Cipher",
    "numberOfInputs",
    "alpha",
    "[object SafariRemoteNotification]",
    "yangcong",
    "height",
    "defineProperty",
    "U",
    "availHeight",
    "token expired",
    "sendMessageToClient",
    "plugin",
    "zSHLaXwGjthqYyplNaUEbjfgzRHC",
    "rPme",
    "Book Antiqua",
    "via",
    "Century Gothic",
    "rgba(255,255,255,1)",
    "iePrivacy",
    "clientIdKey",
    "random",
    "BlockCipherMode",
    "|",
    "storageType",
    "UNSIGNED_BYTE",
    "CBC",
    "zSHlknEgRLQIGZ7eeNUA",
    "h0HQaNwhjU",
    "_TDWSS",
    "NILbyYvb3mp8o048FObdNbmMyIzLYVx8wawxJkT2U8GVUsB/XicXgA3KRRFD+XAz",
    "N",
    "m",
    "zPHvawEejqPqY371eQUeJE",
    "hSHQaIEGRIPIYS7WMr",
    "experimental-webgl",
    "(){[nativecode]}",
    "s38huiupo1g",
    "Promise",
    "failed, path is empty",
    "responseText",
    "_ks",
    "4.0.1",
    "zRzjaKw8Ru",
    "Browser Plug",
    "usage",
    "tIndex",
    "text-rendering",
    "Bookman Old Style",
    "from",
    "onload",
    "Opera",
    "extensionId",
    "dispatchEvent",
    "not a function",
    "getContext",
    "cfg",
    "zRzLINEGRVQqY37bMQUo",
    "map",
    "VConsole",
    "Trident",
    "contentWindow",
    "zoom",
    "safari",
    "onicegatheringstatechange",
    "then",
    "_sz",
    "isTorBrowser",
    "zczwaMwFRIhrGZHSeTU5bEfIzVHKaw",
    "charging",
    "fontFamily",
    "?t=",
    "resize",
    "maximumAge",
    "zPHpanwXjOPFiy7WMrCfJKgjzRRmaQwhjOQrHZHS",
    "_TDWSC",
    "createDynamicsCompressor",
    "reduce",
    "ooQGOO",
    "c",
    "reason",
    "geolocation",
    "td_ua",
    "hSHlJKwhRVhwYp79NNCfJqxNzsHK",
    "RGBA",
    "dec",
    "coords",
    "UNMASKED_VENDOR_WEBGL",
    "\\",
    "_ENC_XFORM_MODE",
    "Lucida Bright",
    "________________",
    "race",
    "state",
    "hash",
    "Firefox",
    "splice",
    "connect",
    "14px 'Arial'",
    "_immediateFn",
    "RegExp",
    "zVzLaNELjKrFYO71MQUEJpfj",
    "VERTEX_SHADER",
    "tokens",
    "q",
    "prlt87lwxvm",
    "Select * from Win32_NetworkAdapterConfiguration Where IPEnabled =True",
    "bindBuffer",
    "hPzmaQEejqrHGF7AMaUVbXxih0Rmaww8RLhR",
    "onunload",
    "orientation",
    "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
    "addons",
    "Arial Hebrew",
    "/web/profile/v1",
    "application/mozilla-npqihooquicklogin",
    "send",
    "mozTCPSocket",
    "Object",
    " OPR/",
    "createEvent",
    "_fmuData",
    "I",
    "application/gameplugin",
    "isPrototypeOf",
    "getDateTimeFormat",
    "BufferedBlockAlgorithm",
    "audiocontext-fingerprint-defender-alert",
    "number",
    "indexedDB",
    "mkcK",
    "PbrD",
    "history",
    "Promise.race accepts an array",
    "Arial",
    "cookieHandler",
    "l",
    "zczwaMwFRIhrGZqbM4C6bF4t",
    "left",
    "ig",
    "start",
    "",
    "https://us-fp.apitd.net",
    "zRzLINEGRVrRYy7FeyUoJg",
    "Times New Roman",
    "getImageData",
    "mc",
    "href",
    "zsHpINELRBhriG7AeqUDJgxs",
    "ywwE",
    "\n",
    "body",
    "2345Explorer",
    "ARRAY_BUFFER",
    "zSHLIDELjIhrHq7FMZUEbXgtzVzma1Eg",
    "Century",
    "iUrl",
    "productSub",
    "drawArrays",
    "00857EDC57927D7E",
    ")",
    "Q",
    "hSHQaIEGREhHYp7A",
    "fromCharCode",
    "htHdaQwhjBhHGZ7WNGUEJqfgz6Hlan",
    "R",
    "getUniformLocation",
    "g",
    "onerror",
    "format",
    "zIzLanEeRLhwYO71eHUEb6xHhSHv",
    "brand",
    "instantiate",
    "application/360softmgrplugin",
    "vertexPosArray",
    "Palatino",
    "_fmOpt.partner is blank, please set the value of _fmOpt.partner and try again!",
    "=; domain=",
    "u",
    "zEwr",
    "platformVersion",
    "s1",
    "mod",
    "pageInfo",
    "name",
    "innerHeight",
    "zSHLaXwGjtQIYO7aeH",
    "fpHost",
    "zVzDIoOcjzhiYOplNGUEJqfgz6Hlan",
    "MS Gothic",
    "txLj",
    "interfaceProtection",
    "drawImage",
    "toFixed",
    "availWidth",
    "boolean",
    "_unhandledRejectionFn",
    "decryptBlock",
    "characterSet",
    "max",
    "no token returned",
    "common2345",
    "a",
    "candidate",
    "onsuccess",
    "ejmK",
    "op",
    "normalDir",
    "Constructor",
    "TripleDES",
    "Microsoft.XMLHTTP",
    "2",
    "MJxC",
    "kernelVersion2",
    "7",
    "maxChannelCount",
    "isSafari",
    "webkitTemporaryStorage",
    "promise",
    "targetActivities",
    "MS Outlook",
    "frameElement",
    "toDataURL",
    "MYRIAD",
    "tdfp",
    "linkProgram",
    "getWebRTC",
    "symbol",
    "beta",
    "opera",
    "HTMLEvents",
    "reliable",
    "zPHvaQwrRIhrGP",
    "appendChild",
    "resolvedOptions",
    "zVzcaQELjCrRYy7FeyUoJg",
    "_hash",
    "timeline",
    "getHighEntropyValues",
    "text-align-last",
    "loseContext",
    "Elzt",
    "Hex",
    "hashchange",
    "status",
    "zPHlaMECjzhriy71eTUpbXxIzS",
    "fontSize",
    "attachEvent",
    "z6HCanEGRVrRYy7FeyUoJg",
    "z6HCanEGRVQqY37bMQUo",
    "dischargingTime",
    "Monaco",
    "_t41",
    "adblock2345",
    "(iPhone|iPod|iPad)(?!.*Safari/)",
    "join",
    "Chromium",
    "TEMPORARY",
    "locale",
    "timeout",
    "T",
    "__defineGetter__",
    "_x64Multiply",
    "setMonth",
    "rtcAvailable",
    "result",
    "mozContacts",
    "mozApps",
    "innerText",
    "devicemotion",
    "-0",
    "n",
    "hp",
    "shaderSource",
    "fmVersion",
    "wb",
    "edit",
    "_deferreds",
    "document",
    "Array.prototype.indexOf() - can't convert `",
    "/web/v2",
    "msMaxTouchPoints",
    "hPzDawEejzhLYG7lMaUeJEfgz1zw",
    "DHDD",
    "createDataChannel",
    "alipay",
    "requestId",
    "@script",
    "path",
    "iPhone",
    "PointerEvent",
    "ceil",
    "[",
    "call",
    "bgMG",
    "A",
    "ABCDEFGHJIKLMNOPQRSTUVWXYZ",
    "catch",
    "audiocontext-defender-alert",
    "Courier",
    "popstate",
    "object",
    "charCodeAt",
    "hasher",
    "fillText",
    "zPHda1EGjlPIi37b",
    "zPzjIKEkRLPIGZ7FeaCEJgxI",
    "S",
    "xAEv",
    "hSHlIwEejUQFGyp2MrUeJqfj",
    "_fmdata",
    "htHdIwEFjzhiGMqYMQCpbKx9z0",
    "zPHda1EGjlPIiY7Ae4UDbpfj",
    "AudioContext",
    "D32F18A11F22776D",
    "Geneva",
    "get",
    "STATIC_DRAW",
    "zJHpanEFRuhLYx7A",
    "sampleRate",
    "gwsF",
    "unpad",
    "iterator",
    "rv:11.0",
    "hostname",
    "screenLeft",
    "altitudeAccuracy",
    "getParameter",
    "granted",
    "isFirefox",
    "Lucida Sans",
    "tor",
    "all",
    "console",
    "substring",
    "attachShader",
    "unload",
    "phantomas",
    "sigBytes",
    "vi",
    "ie",
    "configurable",
    "enumerateDevices",
    "String",
    "Bitstream Vera Sans Mono",
    "getItem",
    "detachEvent",
    "__wxjs_environment",
    "value",
    "prototype",
    "dingtalk",
    "getTime",
    "bufferData",
    "_DEC_XFORM_MODE",
    "font-defender-alert",
    "btoa",
    "log",
    "UNMASKED_RENDERER_WEBGL",
    "msg",
    "kPfK",
    "OfflineAudioContext",
    "style",
    "W",
    "decode",
    "anonymousId",
    "browserVersion2",
    "zJHlaKEkRLhwYO71",
    "screenX",
    "dp",
    "dHJhY2stZnA=",
    "TouchEvent",
    "gesture",
    "offsetUniform",
    "HTMLElement",
    "toLocaleLowerCase",
    "function(){[nativecode]}",
    "valueOf",
    "360EE",
    "_k41",
    "initialization failed",
    "toString",
    "; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;",
    "WEBGL_lose_context",
    "channelCount",
    "serif",
    "behaviorData",
    "webkitOfflineAudioContext",
    "canvas",
    "appVersion,language,languages,mimeTypes,oscpu,platform,plugins,userAgent",
    "ErdG",
    "jmty",
    "on",
    "Arial Unicode MS",
    "h0HLaXEFjCQHYK7blz",
    "accelerationIncludingGravity",
    "referrer",
    "consoleCheck",
    "ajax",
    "not supported",
    "GEwr",
    "Y",
    "zVzcaQELjCQqY37bMQUo",
    "~/=",
    "_nDataBytes",
    "Math",
    "createElement",
    "IE",
    "sine",
    "[object Object]",
    "OpenSSL",
    "Promises must be constructed via new",
    "72px",
    "removeItem",
    "RequestType",
    "F",
    "lineHeight",
    "webkitRequestFileSystem",
    "attrVertex",
    "XDomainRequest",
    "fmData",
    "r1",
    "abs",
    "HMAC",
    "RTCPeerConnection",
    "chrome",
    "detect",
    "Unknown error.The response data is not in JSON format",
    "` to object",
    "vertexAttribPointer",
    "monospace",
    "v",
    "images",
    "Mozilla",
    "Monotype Corsiva",
    "application/asx",
    "MSIE",
    "chargingTime",
    "_lBlock",
    "getAttribLocation",
    "MD5",
    "userAgent",
    ",",
    "behaviorConfigTimestamp",
    "0.0.0.0",
    "z6HcIXEkjGhrHM7YMaUEbFx9",
    "undefined",
    "isUC",
    "scripts",
    "_minBufferSize",
    "JSON",
    "?",
    "clientPort",
    "rotationRate",
    "span",
    "hPzQIKwhjuhDiG7eeqUDJFxmz0HL",
    "CrOS",
    "pTimeout",
    "G",
    "description",
    "Lucida Console",
    "_noScriptPolicy",
    "_",
    "wr",
    "canvas-defender-alert",
    "documentMode",
    "getFloatFrequencyData",
    "000",
    "webkitBattery",
    "os",
    "data=",
    "01FFEFAF1007014E",
    "s2",
    "text/javascript",
    "_x64LeftShift",
    "addres",
    "index",
    "#/",
    "Y2hyb21lLWV4dGVuc2lvbjovL25mZGFhaGhtZmZibGVkZmpsZmVwbGtuaGFlaW5sYmZwL2ljb25zL3N2Zy8=",
    "uwCb",
    "_prevBlock",
    "XMLHttpRequest",
    "CLkC",
    "DeviceMotionEvent",
    "309",
    "ua",
    "2d",
    "browserType2",
    "Verdana",
    "mozPay",
    "_des3",
    "parentNode",
    "permissions",
    "D",
    "c3R1bjpzdHVuLmwuZ29vZ2xlLmNvbToxOTMwMg==",
    "Mac OS",
    "sans-serif",
    "fillRect",
    "disconnect",
    "mozRTCPeerConnection",
    "__proto__",
    "toLowerCase",
    "zSHlaKwGjGhrYppbNaUEbWxIhczwawwr",
    "ms.",
    "h1zjawwrtChLYp79MzUibExI",
    "MSIE (\\d+\\.\\d+);",
    "Edge",
    "compute",
    "Shockwave Flash",
    "font-fingerprint-defender-alert",
    "zsHpIDELjthLGP7aMaeobfxizx",
    "navigator",
    "isChrome",
    "idf",
    "init",
    "suffixes",
    "MSPointerEvent",
    "debug",
    "getIframeScreen",
    "Base",
    "FRAGMENT_SHADER",
    "__IE_DEVTOOLBAR_CONSOLE_COMMAND_LINE",
    "vertexPosAttrib",
    "rejected",
    "getExtension",
    "currentScript",
    "Georgia",
    "z0HLINOFRmPr",
    "globalPrivacyControl",
    "webdriver",
    "id",
    "cssText",
    "#069",
    "detectEthernet",
    "address",
    "zVzLaNELjKQFGPple4U5bE",
    "zczwaMwFRIhrGZqRezCpJdxNzRHChX",
    "_utf8_decode",
    "zVzDIoO7jOhDYy",
    "createShader",
    "mtgC",
    "offsetHeight",
    "FLOAT",
    "blackBox",
    "src",
    "Intl",
    "-&-",
    "Latin1",
    "sessionStorage",
    "CipherParams",
    "taobao",
    "x-pnacl",
    "J",
    "insertBefore",
    "zVzLaNELjKQSY3p2MrUWbF",
    "words",
    "Utf8",
    "Segoe UI",
    "jTimeout",
    "true",
    "mediaDevices",
    "$1",
    "tokenId",
    "string",
    "FDxu",
    "htzwaMwqRzrIYypbezUcJgxNzRHC",
    "filename",
    "SDK error.The encryption of the device information has failed",
    "Cambria Math",
    "check",
    "ActiveXObject",
    "9",
    "enableVertexAttribArray",
    "-9999px",
    "copyWithin",
    "apply",
    "web",
    "ub",
    "(Windows NT 10.0; Win64; x64",
    "Safari",
    "qDej",
    "_fmOpt",
    "_TDctimestamp",
    "writable",
    "script",
    "partner",
    "base64s",
    "Calibri",
    "(",
    "accuracy",
    "pxy",
    "WebAssembly",
    "h77umrlknir",
    "Arial Black",
    "zVHCINELtOPFGM7aeNUJbjfjz6HlanOrRVhHGxpYezCp",
    "onreadystatechange",
    "standalone",
    "resetTime",
    "timeZone",
    "isOpera",
    "encode",
    "EvpKDF",
    "z1HCIwEcjuPSYSpbezefbFfZz6HjawweSIPIGZ7FeqUD",
    " is not iterable(cannot read property Symbol(Symbol.iterator))",
    "query",
    "StreamCipher",
    "ConnectServer",
    "code",
    "xxid",
    "&h=",
    "getTimezoneOffset",
    "Helvetica",
    "Lucida Calligraphy",
    "charset",
    "width",
    "0C9FC1D873BADA42",
    "floor",
    "/behavior/profile/v3?partnerCode=",
    "bAws",
    "sign",
    "application/",
    "userData",
    "WordArray",
    "Pkcs7",
    "GM_addResource",
    "_keyStr",
    "tdIframe",
    "callSelenium",
    "9LzjkIEhqu",
    "z",
    "x-nacl",
    "shift",
    "shopify",
    "zPzDIwOejChLGMpY",
    "attack",
    "atob",
    "itemSize",
    "rtcFinished",
    "complete",
    "Palatino Linotype",
    "Comic Sans MS",
    "kindsOfArray",
    "match",
    "__fpjs_td",
    "currentTime",
    "now",
    "zNzjkIEkRUQIYOpAeNUoK7xiz6HCINwe",
    "reduction"
]

ast = parser.parse(jsCode);

traverse(ast, {
    MemberExpression: function (path) {
        try {
            if(t.isIdentifier(path.node.object)&&path.node.object.name==='QQ0O0'&&t.isNumericLiteral(path.node.property)){
                console.info(path.toString())
                path.replaceWith(
                t.stringLiteral(QQ0O0[path.node.property.value])
            )
            }
        } catch (e) {
        }
    }
})

traverse(ast, {
    StringLiteral: function replace_unicode(path) {
        let node = path.node;
        if (node.extra === undefined) return;
        delete node.extra;
    }
})

fs.writeFileSync('vm411b.js', generator(ast, {minified: true}).code);

console.log('写入操作完成')
